name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Xvfb and Qt libraries
      run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libegl1-mesa libgles2-mesa qt6-base-dev qt6-base-dev-tools
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 &
    - name: Set DISPLAY
      run: export DISPLAY=:99
    - name: Run tests
      run: python run_tests.py