name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Linux system dependencies
      run: |
          # APT update
          sudo apt update
          
          # Install Pyside6 system dependencies
          # https://doc.qt.io/qt-6/linux-requirements.html
          sudo apt install -y \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrender-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libatspi2.0-dev \
            '^libxcb.*-dev'
          sudo apt install -y libxcb-xinerama0
    - name: Install specific PySide6 version
      run: |
        pip uninstall PySide6 -y
        pip uninstall shiboken6 -y
        pip uninstall PySide6_Addons -y
        pip uninstall PySide6_Essentials -y
        pip install PySide6==6.6.1
        pip install shiboken6==6.6.1
    - name: Run tests
      run: xvfb-run python run_tests.py